- hosts: all
  connection: local
  become: true
  # handlers:   # this overrides tumf.systemd-service's handlers...
  #   - include: 'handlers/main.yml'
  vars_files:
    - 'defaults/main.yml'
    - 'vars/main.yml'
  tasks:
    - include: 'tasks/main.yml'
      vars:
        bootstrap_docker_testing: true
