---
# common bootstrapping tasks
- debug: var='{{ item }}'
  with_items: '{{ bootstrap_users }}'

# - name: create users
#   include_role: name=local-user
#   vars: '{{ item | default({}) }}'
#   with_items: '{{ bootstrap_users }}'

- name: install software pre-reqs
  package: '{{ item }}'
  with_items: '{{ bootstrap_packages }}'

- name: install python pre-reqs
  package: '{{ item }}'
  with_items: '{{ bootstrap_pypi_packages }}'

- name: install pre-req ansible roles
  command: 'ansible-galaxy install {{ item }}'
  with_items: '{{ bootstrap_ansible_roles }}'

- name: run pre-req ansible roles
  include_role: name='{{ item }}'
  with_items: '{{ bootstrap_ansible_roles }}'

# set up system to perform last-mile configuration after first boot
# skip if there's no playbook repo set.
- name: install post-imaging playbook for use later
  git:
    repo: '{{ bootstrap_playbook_repo }}'
    dest: /opt/bootstrap/playbook
  when: 'bootstrap_playbook_repo != ""'

- name: check for requirements file in post-imaging playbook
  stat: path=/opt/bootstrap/playbook/requirements.yml
  register: stat_reqs
  when: 'bootstrap_playbook_repo != ""'

- name: install post-imaging playbook pre-requisites
  command: 'ansible-galaxy install -r /opt/bootstrap/playbook/requirements.yml'
  when:
    - 'stat_reqs.stat.exists == True'
    - 'bootstrap_playbook_repo != ""'

- name: drop vars file for post-launch playbook to use
  copy:
    content: '{{ bootstrap_playbook_vars | to_yaml }}'
    dest: '/opt/bootstrap/playbook_vars.yml'
  when: 'bootstrap_playbook_repo != ""'

# i got rid of the block surrounding everything from "set up system to perform..."
# i got rid of the vars in this block
# i got rid of the when.
# still, i get this error: ERROR! this task 'include_role' has extra params, which is only allowed in the following modules: command, win_command, shell, win_shell, script, include, include_vars, add_host, group_by, set_fact, raw, meta
- name: drop systemd service to do post-launch configuration
  include_role: systemd-service
